### PR TITLE
Implement muon.crypto.encryptString/decryptString API

### PR DESCRIPTION
**Pull request by darkdh**
master key is same as built-in password manager/cookies
Using base64 to encode non ASCII characters

fix https://github.com/brave/browser-laptop/issues/10705

Auditors: @bridiver, @diracdeltas, @bbondy

### CODE REVIEW

**Comment by darkdh** [comment]
@bsclifton mentioned this might cause manually session backup failed because you can only encrypt/decrypt value on the same machine.
What do you think @diracdeltas ?

**Comment by darkdh** [comment]
saved password and cookies applied to the same rules ^^^
so you can just copy those file to different machine

**Comment by diracdeltas** [comment]
for safety, i think that muon.crypto.encryptString/decryptString should throw an error or return nothing if OSCrypt `EncryptString/DecryptString` are not available. In most cases, if a string cannot be encrypted, it is better to save nothing than to save it in plaintext.

**Comment by bridiver** [comment]
wouldn't it be better to just store them in the password manager? That has the added benefit of cross-device sync

**Comment by darkdh** [comment]
we can do that on Mac and Window because password manager stores encrypted password in `Login Data` sql file but it stores the login entries in keyring

**Comment by diracdeltas** [comment]
cc @riastradh for review of the underlying chromium crypto code

**Pull request merged**
