### PR TITLE
skip over master brave window when querying brave/browser-laptop#8811

### PR DESCRIPTION
**Pull request by kevinlawler**

### CODE REVIEW

**Comment by kevinlawler** [comment]
One of the issues with that is `-1` already indicates `WINDOW_ID_NONE`. Normally I would agree, but in this instance it's probably better to filter on something more definitely unique to the main Brave window. (Perhaps, it should have a special key set on its object.) That said, `-1` will (should) still work if we decide to change it.

**Comment by jonathansampson** [comment]
@kevinlawler I'm not 100% `.url.indexOf('chrome://')` will match only the Brave frame. We could also check that the title matches `/^brave$/i` to be certain.

```
{
    "active": false,
    "audible": false,
    "autoDiscardable": true,
    "discarded": false,
    "height": 1050,
    "highlighted": false,
    "id": 1,
    "incognito": true,
    "index": -1,
    "mutedInfo": {
        "muted": false,
        "reason": "user"
    },
    "pinned": false,
    "selected": false,
    "status": "complete",
    "title": "Brave",
    "url": "chrome://brave/C:/Users/jjdsa/AppData/Local/brave/app-0.15.303/resources/app.asar/app/extensions/brave/index.html",
    "width": 1922,
    "windowId": -1
}
```

**Comment by kevinlawler** [comment]
OK, I'll match against `-1` then unless there are objections. 

Matching against `title=="Brave"` I think gives us the same problem before: false positives are improbable but a possible bug nonetheless.

**Comment by jonathansampson** [comment]
I wasn't suggesting a single check, but rather "chrome://" _and_ "Brave" 🙂 Either one alone could yield false positives indeed. We'll, "chrome://" may not—I'm not sure.

**Comment by bridiver** [comment]
definitely not save to check for `indexOf('chrome://')`, but `indexOf('chrome://brave')` would be safe

**Comment by jonathansampson** [comment]
Thanks, @bridiver. @kevinlawler, how about `tab.url.startsWith('chrome://brave/')`?

**Comment by bridiver** [comment]
sorry I've let this one sit forever. Is this safe to merge for the next build? Doesn't require any browser-laptop changes?

**Comment by jonathansampson** [comment]
@bridiver No changes to _browser-laptop_.

**Comment by bridiver** [comment]
ok, I'll merge and look at removing the TabHelper instead when I have time

**Comment by jonathansampson** [comment]
Resolves https://github.com/brave/browser-laptop/issues/8822.

@bridiver, do you know when this should appear in preview builds? Still repros for me in 0.19.0 (https://github.com/brave/browser-laptop/commit/c5968c5ea2a8eaab1834d638aa4ead5af5d517e2).

**Comment by bridiver** [comment]
It should be in 4.1 builds for muon

**Pull request merged**
