### PR TITLE
Ask user consent before autofill

### PR DESCRIPTION
**Pull request by darkdh**
fix https://github.com/brave/browser-laptop/issues/6558

required by https://github.com/brave/browser-laptop/pull/12835

Auditors: @bridiver, @diracdeltas, @bbondy 
kapture 2018-01-24 at 15 33 28

### CODE REVIEW

**Comment by darkdh** [comment]
working on getting user consent before filling fields

**Comment by darkdh** [comment]
ready for review

**Comment by diracdeltas** [comment]
i ran into some build errors:

```
In file included from ../../electron/atom/browser/autofill/atom_autofill_client.cc:5:
../../electron/atom/browser/autofill/atom_autofill_client.h:99:72: error: only virtual member functions can be marked 'override'
  void DidGetAutofillValues(const std::vector<base::string16>& values) override;
                                                                       ^~~~~~~~
../../electron/atom/browser/autofill/atom_autofill_client.cc:90:16: error: no member named 'QueryAutofillValues' in 'autofill::AutofillPopupDelegate'
    delegate_->QueryAutofillValues(frontend_id);
    ~~~~~~~~~  ^
2 errors generated.
```

**Comment by darkdh** [comment]
@diracdeltas that is because we have new chromium patch changes in this PR.
run `./script/apply-patches.py` in `browser-laptop-bootstrap/src/electron` and build again

**Comment by diracdeltas** [comment]
@darkdh oops, thank you. for some reason i thought that was run automatically when the build starts

**Pull request closed without merging**
